### PR TITLE
Correcting type conflicts

### PR DESCRIPTION
**Pull request by hassaanhashmi**

### CODE REVIEW

**Comment by dmiklic** [comment]
Hi @hassaanhashmi, can you please elaborate a bit on the issue this PR is supposed to resolve?

**Comment by hassaanhashmi** [comment]
Sure; some class objects were assigned boolean values which gave errors during the build process. I just changed the `false` values to `NULL` and the library was built successfully.

**Comment by dmiklic** [comment]
Thanks for the additional info, and sory for the delays in my replies, I have a lot of stuff going on right now. Anyways, could you please replace `NULL` by `nullptr` in your PR. Not that it makes a big difference in this particular case, but it [conforms to modern C++ syntax](https://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced).

**Comment by hassaanhashmi** [comment]
Thank you for the reply. I apologize for the late response, but I have now replaced `NULL` by `nullptr`.

**Comment by dmiklic** [comment]
Thanks, looks good. Could you please squash the commits before I merge?

**Comment by hassaanhashmi** [comment]
I have fixed up the last commit. Please do let me know if you require anything else before the merge.

**Pull request merged**
